name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |
        docker logout
        echo '${{ secrets.DOCKERPASSWORD }}' | docker login -u '${{ secrets.DOCKERUSERNAME }}' --password-stdin
        docker image build -t jontismo/task-tracker-rs .
        docker tag jontismo/task-tracker-rs jontismo/task-tracker-rs
        docker push jontismo/task-tracker-rs
