name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |
        docker logout
        echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
        docker image build -t '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs .
        docker tag '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
        docker push '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
        docker image rm '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop & Remove old container and image
        run: |
          ssh deploy 'CONTAINERID=$(docker ps -q --filter "publish=8080") && docker stop "$CONTAINERID" && docker rm "$CONTAINERID" && docker image rm jontismo/task-tracker-rs'

      - name: Pull & Run new container
        run: |
          ssh deploy "docker pull '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs &&  docker run -d -p 8080:8080 -v /home/jon/task-data:/app/data --network traefik_default --label traefik.enable=true --label traefik.http.routers.task-tracker-rs.entrypoints=web,websecure --label traefik.http.routers.task-tracker-rs.rule=Host(\`tasks.nurminen.io\`) --label traefik.http.routers.task-tracker-rs.tls=true --label traefik.http.routers.task-tracker-rs.tls.certresolver=production --restart always '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs"
