name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |
        docker logout
        echo '${{ secrets.DOCKERPASSWORD }}' | docker login -u '${{ secrets.DOCKERUSERNAME }}' --password-stdin
        docker image build -t '${{ secrets.DOCKERUSERNAME }}'/task-tracker-rs .
        docker tag '${{ secrets.DOCKERUSERNAME }}'/task-tracker-rs '${{ secrets.DOCKERUSERNAME }}'/task-tracker-rs
        docker push '${{ secrets.DOCKERUSERNAME }}'/task-tracker-rs
        docker image rm '${{ secrets.DOCKERUSERNAME }}'/task-tracker-rs
