name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and push image
      run: |
        echo '${{ secrets.DOCKERPW }}' | docker login -u "jontismo" --password-stdin
        docker image build -t task-tracker-rs/task-tracker:v1 .
        docker push task-tracker-rs/task-tracker:v1
