name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and push image
      run: |
        docker logout
        echo '${{ secrets.DOCKERPW }}' | docker login -u "jontismo" --password-stdin
        docker image build -t jontismo/task-tracker-rs .
        docker tag jontismo/task-tracker-rs jontismo/task-tracker-rs
        docker push jontismo/task-tracker-rs
