name: Task tracker

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |
        docker logout
        echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
        docker image build -t '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs .
        docker tag '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
        docker push '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
       # docker image rm '${{ secrets.DOCKER_USERNAME }}'/task-tracker-rs
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo '${{ secrets.SSH_KNOWN_HOSTS }}' > ~/.ssh/known_hosts

      - name: Stop & Remove old container and image
        run: |
          ssh -i ~/.ssh/private.key jon@nurminen.io 'CONTAINERID=$(docker ps -q --filter "publish=8080") && docker stop "$CONTAINERID" && docker rm "$CONTAINERID" && docker image rm jontismo/task-tracker-rs'

      - name: Pull & Run new container
        run: |
          ssh -i ~/.ssh/private.key jon@nurminen.io 'docker pull "${{ secrets.DOCKER_USERNAME }}"/task-tracker-rs &&  docker run -d -p 127.0.0.1:8080:8080 -v /home/jon/task-data:/app/data --network traefik_default --restart always "${{ secrets.DOCKER_USERNAME }}"/task-tracker-rs'
